<div>   <div class="plat-rightMain"><section class="manageWork"><div class="platform-con chapterFigure"><div class="cartoonCrumbs"><a href="/writings/book" class="selected">作品管理</a> <a href="/writings/book" class="selected">&gt; 文学作品</a> <a href="/writings/book/100196352/chapter?bookName=%E5%B9%BD%E5%B7%9E%E5%88%A4%E5%AE%98" class="selected">&gt; 章节管理</a> <span> &gt; 写新章节</span> <!----></div> <div class="chapterWrap"><dl class="chapterInfo"><dt>幽州判官</dt> <dd><span class="popup-redstar">*</span> <label for="">发布至卷</label> <div class="workSel juanSel"><!----> <span class="groupNameInput">第1卷：正文</span> <ul class="selectList dn"><li><a href="javascript:;">第1卷：正文</a></li></ul></div> <a href="javascript:;" rseat="705021_wenxue27" class="addJuanLink">加卷</a></dd> <dd><span class="popup-redstar">*</span> <label for="">章节名称</label> <input type="text" placeholder="20字之内，示例：第1章：黄山奇遇" data-vv-rules="required|max:20|checkSenstive" data-vv-name="name" class="cartoonInput w228" data-vv-id="_ij2mqeyh9" aria-required="true" aria-invalid="false"> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                
                            </span></span> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                本章为付费章节，若需要修改章节，请联系编辑！
                            </span></span> <span class="chapterNum" style="padding-left: 10px; display: none;">自动保存于：</span> <span class="chapterNum">字数统计：<em>0</em></span></dd></dl> <div class="editNovelChapter-wrap"><textarea placeholder="请输入正文，首次发布文章不得少于1000字" data-vv-rules="required" data-vv-name="content" class="novelChapter-textarea" data-vv-id="_yhkvd43a7" aria-required="true" aria-invalid="false"></textarea></div> <p style="color: rgb(255, 0, 0); display: none;">
                        
                    </p> <div class="mh-btnWrap"><a href="/writings/book/100196352/chapter?bookName=%E5%B9%BD%E5%B7%9E%E5%88%A4%E5%AE%98" class="handleBtn handleBtn-gray selected">取消</a> <!----> <a href="javascript:void(0)" rseat="705021_wenxue29" class="handleBtn handleBtn2">
                            存草稿
                        </a> <a href="javascript:void(0)" rseat="705021_wenxue28" class="handleBtn">
                            提交发布
                        </a> <!----> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                本章为付费章节，修改后字数不能少于当前字数！
                            </span></span></div></div></div></section> <div class="pf-loading-bg" style="z-index: 1100; display: none;"><div class="popup popup-chapterPublish" style="position: fixed; top: 50%; left: 50%; margin-top: -240px; margin-left: -216px; z-index: 101;"><div class="public-popTitle clearfix"><span class="popTitle">章节发布</span> <i class="pf_icon pf_icon-popClose"></i></div> <div class="popup-body "><div class="chapterPublish-wrap"><p>确定发布后章节提交审核，审核通过的文章读者可见！</p> <ul class="chapterCheckList"><li><span class="chapterCheckTitle">发布章节</span>：<span class="chapterCheckCon"></span></li> <li><span class="chapterCheckTitle">所在卷</span>：<span class="chapterCheckCon">第1卷：正文</span></li> <li><span class="chapterCheckTitle">定时发布</span>：
                        <span class="chapterCheckCon"><span rseat="705021_wenxue30" class="mh-handleBtn"><i class="pf_icon pf_icon-checkbox2"></i>是
                            </span></span></li> <li style="position: relative; display: none;"><span class="chapterCheckTitle">发布时间</span>：<span class="chapterCheckCon"></span> <input type="text" readonly="readonly" placeholder="定时发布时间" data-vv-rules="required|checkTime" data-vv-name="releaseTime" class="chapterTime flatpickr-input" data-vv-id="_8mpc8asxd" aria-required="true" aria-invalid="false" style="z-index: 201; display: none;"> <span class="chapterCheckTitle" style="cursor: pointer; color: rgb(29, 193, 96);">
                            智能推荐
                        </span> <i class="questionTip" style="margin-left: 0px;"><div class="triangle-tip"><i class="icon-triangle"></i> <span class="tip-txt">
                                    智能推荐是综合分析历史上作品发布时间与点击量、收藏量、订阅量、收入等指标的相关关系推算的最优发布时间，再次点击可更换时间
                                </span></div></i> <p style="color: rgb(255, 0, 0); display: none;">
                            
                        </p></li></ul></div></div> <div class="popup-operation tc"><a href="javascript:;" class="workPopBtn1">确认发布</a> <a href="javascript:;" class="workPopBtn2">取消</a></div></div></div> <!----> <!----></div> <div class="iopen-scrollBar"><!----> <ul class="plat-scrollbar-inner"><li><div class="outer"><i class="mp-svgicon svg-opinion"></i> <span class="text" rseat="rf_yjfk" dt="b">意见反馈</span></div></li> <!---->  <!----> <li><div class="outer"><i class="mp-svgicon svg-sidebarQuestion"></i> <span class="text">常见问题</span></div></li> <li title="回顶部" alt="回顶部"><div class="outer"><i class="mp-svgicon svg-toTop"></i> <span class="text">返回顶部</span></div></li></ul></div></div>