<div>   <div class="plat-rightMain"><section class="manageWork"><div class="platform-con addComics"><div class="cartoonCrumbs"><a href="/writings/book" class="selected">作品管理</a> <a href="/writings/book" class="selected">&gt; 文学作品</a> <span> &gt; 新建作品</span></div> <div class="addNovel-con"><div class="workTip">作品信息中不能含有违法违规信息，如色情、反动、违反主流道德观等有害信息。</div> <div class="addNovelForm-wrap"><ul class="addNovelForm"><li class="novelForm-item1"><label for="" class="workLabel"><i class="mustStar">*</i>
                                    作品名称
                                </label> <input type="text" placeholder="18字以内，请不要填写书名号等特殊字符" data-vv-rules="required|checkNameFomat|checkname|max:18|checkSenstive|signCheck" data-vv-name="name" class="workInput" data-vv-id="_dvc4lo40r" aria-required="true" aria-invalid="false"> <span class="workFormTip" style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                    
                                </span></span></li> <li class="novelForm-item2"><label for="" class="workLabel"><i class="mustStar">*</i>
                                    作品介绍
                                </label> <span class="workTextarea-wrap "><textarea placeholder="用20~500字介绍作品内容" data-vv-rules="required|min:20|max:500|checkSenstive" data-vv-name="desp" class="workTextarea" data-vv-id="_tmij0jir1" aria-required="true" aria-invalid="false"></textarea> <span class="wordNum">0/500</span></span> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                    
                                </span></span></li> <!----> <li class="novelForm-item3"><label for="" class="workLabel"><i class="mustStar">*</i>
                                    作品分类
                                </label> <div class="workSel novelSel"><!----> <span class="groupNameInput">文学</span> <ul class="selectList dn"><li><a href="javascript:;">文学</a></li></ul></div> <div class="workSel novelSel2"><!----> <span class="groupNameInput">其他</span> <ul class="selectList dn"><li><a href="javascript:;">其他</a></li><li><a href="javascript:;">青春</a></li><li><a href="javascript:;">家庭</a></li><li><a href="javascript:;">军事</a></li><li><a href="javascript:;">都市</a></li><li><a href="javascript:;">现代言情</a></li><li><a href="javascript:;">古代言情</a></li><li><a href="javascript:;">历史</a></li><li><a href="javascript:;">悬疑</a></li><li><a href="javascript:;">幻想</a></li><li><a href="javascript:;">职场</a></li><li><a href="javascript:;">惊悚</a></li><li><a href="javascript:;">非虚构</a></li><li><a href="javascript:;">儿童</a></li><li><a href="javascript:;">中短篇</a></li><li><a href="javascript:;">轻小说</a></li></ul></div> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                    
                                </span></span></li> <li class="novelForm-item4"><label for="" class="workLabel"><i class="mustStar">*</i>
                                    作品标签
                                </label> <div work-tagsort="workTagSort" data-vv-rules="required|checkTagCount:4,6" data-vv-name="selectedTags" data-vv-id="_2zbw4bq07" aria-required="true" aria-invalid="false" style="display: inline-block;"><div class="wordTagWrap"> <div class="workTagSelect" style="display: none;"><div class="workTagSelect-title">
                    选择标签(4~6个)
                 <!----> <!----> <i class="pf_icon pf_icon-popClose"></i></div> <div class="workTagSelect-con"></div></div></div> <a href="javascript:;" class="addWorkTagBtn"></a></div> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                    
                                </span></span></li> <li class="novelForm-item5"><label for="" class="workLabel"><i class="mustStar">*</i>
                                    授权级别
                                </label> <div class="iptWrap" data-vv-rules="required" data-vv-name="authLevel" data-vv-id="_h69ystn4c" aria-required="true" aria-invalid="false"><span class="pgc-content-type"><i class="pf-icon pf-radio-new"></i><em>普通授权</em></span><span class="pgc-content-type"><i class="pf-icon pf-radio-new"></i><em>独家首发</em></span> </div> <i class="mp-svgicon svg-questionMark"><div class="tooltip-white tooltip-white_bottom"><i class="tooltip-triangle"></i> <p class="tip-txt c-999">普通授权：在爱奇艺文学发表的原创作品；</p> <p class="tip-txt c-999">独家首发：首次发表且只在爱奇艺文学发表的原创作品。</p></div></i> <span class="workFormTip " style="display: none;"><i class="workForm-angel"></i> <span class="workFormTip-con">
                                    
                                </span></span></li> <!----> <li class="novelForm-item7"><label for="" class="workLabel">
                                   作品封面
                                </label> <div class="workCover"><div style="width: 150px; height: 200px; overflow: hidden;"><img src="//www.iqiyipic.com/common/fix/public-platform/temporaryCover.png" alt="" id="uploadPreview"></div> <a href="javascript:;" class="workBtn uploadCoverBtn">本地上传</a></div></li></ul> <div class="addWork-submit"><a href="/writings/book" class="workBtn cancelWorkBtn mr20 selected">取消</a> <!----> <a href="javascript:;" class="workBtn saveWorkBtn">
                                创建作品
                            </a></div></div></div></div> <div class="pf-loading-bg" style="z-index: 1100; display: none;"><div class="popup popup-workClip" style="position: fixed; z-index: 100; top: 50%; left: 50%; margin-left: -254px; margin-top: -178px;"><div class="public-popTitle clearfix"><span class="popTitle">作品封面</span> <i class="pf_icon pf_icon-popClose"></i></div> <div class="popup-body "><div class="workClip-wrap clearfix"><div class="workClipLeft"><img id="crop" src="" alt="" class="bigClip" style="width: 100%;"></div> <div class="workClipright" style="position: relative;"><a href="javascript:;" class="selectClipCover" style="position: relative; z-index: 1;">选择文件</a> <p>建议尺寸：600X800px</p> <p>格式：jpg、png、jpeg</p> <p>大小：不超过5M</p> <div data-portal-elem="cropView" id="preView" class="smallClipOuter" style="position: relative; overflow: hidden;"></div><div id="html5_1dba2np921rj4183s1jke174e11ccj_container" class="moxie-shim moxie-shim-html5" style="position: absolute; top: 0px; left: 0px; width: 0px; height: 0px; overflow: hidden; z-index: 0;"><input id="html5_1dba2np921rj4183s1jke174e11ccj" type="file" style="font-size: 999px; opacity: 0; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;" accept=".jpg,.jpeg,.png"></div></div></div></div> <div class="popup-operation tc"><a href="javascript:;" class="workPopBtn4 mr10">取消</a> <a href="javascript:;" class="workPopBtn3">确认</a></div></div></div></section> <layer></layer> <!----></div> <div class="iopen-scrollBar"><!----> <ul class="plat-scrollbar-inner"><li><div class="outer"><i class="mp-svgicon svg-opinion"></i> <span class="text" rseat="rf_yjfk" dt="b">意见反馈</span></div></li> <!---->  <!----> <li><div class="outer"><i class="mp-svgicon svg-sidebarQuestion"></i> <span class="text">常见问题</span></div></li> <li title="回顶部" alt="回顶部"><div class="outer"><i class="mp-svgicon svg-toTop"></i> <span class="text">返回顶部</span></div></li></ul></div></div>